include:
  - project: infrastructure/gitlab-templates
    ref: main
    file: node-full.yml

variables:
  SOURCE_PROJECT_NAME: developer-portal
  IMAGE: koperator-internal/documentation/developer-portal

build:
  before_script:
    - npm config set //gitlab.cloudpirates.io/api/v4/packages/npm/:_authToken ${CI_JOB_TOKEN}
    - npm ci --cache .npm --prefer-offline
    - apk add git

release:image:
  extends: .release
  trigger:
    project: koperator/infrastructure/kubernetes
    branch: main
